//
//  Theme.m
//  Practice
//
//  Created by Ibrahim on 20/05/2016.
//  Copyright © 2016 Ibrahim. All rights reserved.
//


// IMPORT

#import "Font Size.h"


// IMPLEMENTATION

    // GENERAL

    CGFloat const FONT_SIZE_GENERAL = 21;


    // NAVIGATION

    CGFloat const FONTSIZE_NAVIGATION_NAME = FONT_SIZE_GENERAL + 13;
    CGFloat const FONTSIZE_NAVIGATION_POSITION = FONT_SIZE_GENERAL - 9;
    CGFloat const FONTSIZE_NAVIGATION_HEADER = FONT_SIZE_GENERAL - 7;
    CGFloat const FONTSIZE_NAVIGATION_DETAIL = FONT_SIZE_GENERAL - 9;

    // HEADER

    CGFloat const FONTSIZE_HEADER_TITLE = FONT_SIZE_GENERAL + 3;
    CGFloat const FONTSIZE_HEADER_PARENT = FONT_SIZE_GENERAL - 7;

    // GUIDE

        // GUIDE HEADER

        CGFloat const FONTSIZE_GUIDEHEADER_STEP = FONT_SIZE_GENERAL + 15;
        CGFloat const FONTSIZE_GUIDEHEADER_TITLE = FONT_SIZE_GENERAL;
        CGFloat const FONTSIZE_GUIDEHEADER_DETAIL = FONT_SIZE_GENERAL - 7;
        CGFloat const FONTSIZE_GUIDEHEADER_STATE = FONT_SIZE_GENERAL - 11;

        // GUIDE DETAIL

        CGFloat const FONTSIZE_GUIDEDETAIL_STEP = FONT_SIZE_GENERAL;

    // CONTENT

    CGFloat const FONTSIZE_CONTENT_HEADER = FONT_SIZE_GENERAL - 2;
    CGFloat const FONTSIZE_CONTENT_GENERAL = FONT_SIZE_GENERAL - 2;

    // POINT

    CGFloat const FONTSIZE_POINT_CIRCLE = FONT_SIZE_GENERAL;
    CGFloat const FONTSIZE_POINT_HEADER = FONT_SIZE_GENERAL - 4;
    CGFloat const FONTSIZE_POINT_DETAIL = FONT_SIZE_GENERAL - 8;

    // BUTTON

    CGFloat const FONTSIZE_FORM_BUTTON = FONT_SIZE_GENERAL;
    CGFloat const FONTSIZE_NAVIGATION_BUTTON = FONT_SIZE_GENERAL - 4;